import type { Layer, OperationType } from '../../types/project';
import { LBRN_PALETTE_COLORS, PALETTE_COLORS } from '../../constants/palette';

/** Names the backend assigns by default — treat these as "no custom name". */
const DEFAULT_LAYER_NAMES = new Set(['Line', 'Fill', 'Offset Fill', 'Image', 'Cut', 'Score']);

/** Normalize color tag for comparison — strip alpha suffix, lowercase. */
export function normalizeHex(hex: string): string {
  let h = hex.toLowerCase().trim();
  // Strip 8-char RGBA to 6-char RGB (e.g. #ff0000ff → #ff0000)
  if (h.length === 9 && h.startsWith('#')) h = h.slice(0, 7);
  return h;
}

function autoFamilyLabel(name: string | undefined): string | null {
  const match = name?.trim().match(/^([CT]\d+)(?:\s+\((?:Image|Line|Cut|Score|Fill|Offset Fill)\))?$/);
  return match?.[1] ?? null;
}

function lbrnPaletteIndex(layer: Layer): number | null {
  const label = autoFamilyLabel(layer.name);
  if (!label) return null;
  const index = label.startsWith('T')
    ? Number(label.slice(1)) + 29
    : Number(label.slice(1));
  if (!Number.isInteger(index) || index < 0 || index >= LBRN_PALETTE_COLORS.length) {
    return null;
  }
  return normalizeHex(LBRN_PALETTE_COLORS[index]) === normalizeHex(layer.color_tag)
    ? index
    : null;
}

function paletteLabel(index: number): string {
  return index >= 30 ? `T${index - 29}` : `C${String(index).padStart(2, '0')}`;
}

export function getLayerLabel(layer: Layer): string {
  const sourceIndex = lbrnPaletteIndex(layer);
  if (sourceIndex !== null) return paletteLabel(sourceIndex);

  const colorTag = layer.color_tag;
  const norm = normalizeHex(colorTag);
  const idx = PALETTE_COLORS.findIndex(
    (c) => normalizeHex(c.hex) === norm,
  );
  if (idx >= 0) {
    return paletteLabel(idx);
  }
  // Fallback: use order_index
  return `C${String(layer.order_index).padStart(2, '0')}`;
}

export function operationDisplayLabel(op: OperationType): string {
  switch (op) {
    case 'tool': return 'Tool';
    case 'image': return 'Image';
    case 'line': return 'Line';
    case 'cut': return 'Cut';
    case 'score': return 'Score';
    case 'fill': return 'Fill';
    case 'offset_fill': return 'Offset Fill';
  }
}

function primaryEntry(layer: Layer) {
  return layer.entries[0];
}

export function layerOperation(layer: Layer): OperationType {
  return primaryEntry(layer)?.operation ?? 'line';
}

/** Matches auto-generated family labels like "C00", "C01", "T1", "T2". */
const AUTO_FAMILY_LABEL_RE = /^[CT]\d+$/;

/** Matches auto-generated sibling names like "C02 (Image)", "T1 (Line)". */
const AUTO_SIBLING_NAME_RE = /^[CT]\d+\s+\((Image|Line|Cut|Score|Fill|Offset Fill)\)$/;

export function isAutoGeneratedFamilyName(layer: Layer): boolean {
  const name = layer.name?.trim();
  if (!name) return true;
  if (DEFAULT_LAYER_NAMES.has(name)) return true;
  // Match current family label or any stale palette-style label (C##, T#).
  // This catches names like "C02 (Image)" that became stale after recolor.
  if (AUTO_FAMILY_LABEL_RE.test(name)) return true;
  if (AUTO_SIBLING_NAME_RE.test(name)) return true;
  const familyLabel = getLayerLabel(layer);
  if (name === familyLabel) return true;
  return name === `${familyLabel} (${operationDisplayLabel(layerOperation(layer))})`;
}

export function displayLayerName(layer: Layer): string {
  return isAutoGeneratedFamilyName(layer)
    ? getLayerLabel(layer)
    : layer.name;
}
