import { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { useProjectStore } from '../../stores/projectStore';
import { useUiStore } from '../../stores/uiStore';
import { useAppStore } from '../../stores/appStore';
import { projectService } from '../../services/projectService';
import { NumberInput } from '../shared/NumberInput';
import { CutSettingsEditor } from './CutSettingsEditor';
import { ContextMenu } from '../shared/ContextMenu';
import { buildLayerContextMenuItems } from './layerMenuItems';
import { buildLayerListHeaderMenuItems } from './LayerListHeaderMenu';
import { LBRN_PALETTE_COLORS, PALETTE_COLORS } from '../../constants/palette';
import { useNotificationStore } from '../../stores/notificationStore';
import { CheckSquare, ClipboardCopy, ClipboardPaste, Lock } from 'lucide-react';
import type { Layer, OperationType, VectorSettings } from '../../types/project';
import { effectiveLineIntervalMm } from '../../types/rasterSettings';
import {
  displaySpeedToMmMin,
  formatSpeedForDisplay,
  speedInputValue,
  speedMmMinToDisplay,
  speedStepForUnit,
  speedUnitLabel,
} from '../../utils/speedUnits';
import { mmToDisplay, displayToMm, roundDisplayLength, lengthStep, lengthUnitLabel, labelWithUnit } from '../../utils/lengthUnits';

const MODE_OPTIONS: { value: OperationType; labelKey: string }[] = [
  { value: 'line', labelKey: 'panels.layers.mode.line' },
  { value: 'fill', labelKey: 'panels.layers.mode.fill' },
  { value: 'offset_fill', labelKey: 'panels.layers.mode.offset_fill' },
];

const MOVE_UP_ICON = '\u25B2';
const MOVE_DOWN_ICON = '\u25BC';
const SHOW_TOGGLE_ACTIVE_COLOR = 'bg-bb-accent';
const AIR_TOGGLE_ACTIVE_COLOR = 'bg-yellow-500';

/** Names the backend assigns by default — treat these as "no custom name". */
const DEFAULT_LAYER_NAMES = new Set(['Line', 'Fill', 'Offset Fill', 'Image', 'Cut', 'Score']);

/** Normalize color tag for comparison — strip alpha suffix, lowercase. */
function normalizeHex(hex: string): string {
  let h = hex.toLowerCase().trim();
  // Strip 8-char RGBA to 6-char RGB (e.g. #ff0000ff → #ff0000)
  if (h.length === 9 && h.startsWith('#')) h = h.slice(0, 7);
  return h;
}

function autoFamilyLabel(name: string | undefined): string | null {
  const match = name?.trim().match(/^([CT]\d+)(?:\s+\((?:Image|Line|Cut|Score|Fill|Offset Fill)\))?$/);
  return match?.[1] ?? null;
}

function lbrnPaletteIndex(layer: Layer): number | null {
  const label = autoFamilyLabel(layer.name);
  if (!label) return null;
  const index = label.startsWith('T')
    ? Number(label.slice(1)) + 29
    : Number(label.slice(1));
  if (!Number.isInteger(index) || index < 0 || index >= LBRN_PALETTE_COLORS.length) {
    return null;
  }
  return normalizeHex(LBRN_PALETTE_COLORS[index]) === normalizeHex(layer.color_tag)
    ? index
    : null;
}

function paletteLabel(index: number): string {
  return index >= 30 ? `T${index - 29}` : `C${String(index).padStart(2, '0')}`;
}

function getLayerLabel(layer: Layer): string {
  const sourceIndex = lbrnPaletteIndex(layer);
  if (sourceIndex !== null) return paletteLabel(sourceIndex);

  const colorTag = layer.color_tag;
  const norm = normalizeHex(colorTag);
  const idx = PALETTE_COLORS.findIndex(
    (c) => normalizeHex(c.hex) === norm,
  );
  if (idx >= 0) {
    return paletteLabel(idx);
  }
  // Fallback: use order_index
  return `C${String(layer.order_index).padStart(2, '0')}`;
}

function operationDisplayLabel(op: OperationType): string {
  switch (op) {
    case 'tool': return 'Tool';
    case 'image': return 'Image';
    case 'line': return 'Line';
    case 'cut': return 'Cut';
    case 'score': return 'Score';
    case 'fill': return 'Fill';
    case 'offset_fill': return 'Offset Fill';
  }
}

function primaryEntry(layer: Layer) {
  return layer.entries[0];
}

function layerOperation(layer: Layer): OperationType {
  return primaryEntry(layer)?.operation ?? 'line';
}

function primaryRasterSettings(layer: Layer) {
  return primaryEntry(layer)?.raster_settings ?? null;
}

function primaryVectorSettings(layer: Layer) {
  return primaryEntry(layer)?.vector_settings ?? null;
}

/** Matches auto-generated family labels like "C00", "C01", "T1", "T2". */
const AUTO_FAMILY_LABEL_RE = /^[CT]\d+$/;

/** Matches auto-generated sibling names like "C02 (Image)", "T1 (Line)". */
const AUTO_SIBLING_NAME_RE = /^[CT]\d+\s+\((Image|Line|Cut|Score|Fill|Offset Fill)\)$/;

function isAutoGeneratedFamilyName(layer: Layer): boolean {
  const name = layer.name?.trim();
  if (!name) return true;
  if (DEFAULT_LAYER_NAMES.has(name)) return true;
  // Match current family label or any stale palette-style label (C##, T#).
  // This catches names like "C02 (Image)" that became stale after recolor.
  if (AUTO_FAMILY_LABEL_RE.test(name)) return true;
  if (AUTO_SIBLING_NAME_RE.test(name)) return true;
  const familyLabel = getLayerLabel(layer);
  if (name === familyLabel) return true;
  return name === `${familyLabel} (${operationDisplayLabel(layerOperation(layer))})`;
}

function displayLayerName(layer: Layer): string {
  return isAutoGeneratedFamilyName(layer)
    ? getLayerLabel(layer)
    : layer.name;
}

const COL_TEMPLATE = '28px 40px 72px 1fr 18px';
//                     #    Layer  Mode  Spd/Pwr Out  Show  Air   arrows
const COL_GAP = 'gap-x-3';

/** Return '#fff' or '#000' for best contrast against a hex background. */
function getContrastText(hex: string): string {
  const h = hex.replace('#', '');
  const r = parseInt(h.substring(0, 2), 16);
  const g = parseInt(h.substring(2, 4), 16);
  const b = parseInt(h.substring(4, 6), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 > 128 ? '#000' : '#fff';
}

/** Get the palette index number for the layer chip display. */
function getPaletteIndex(layer: Layer): string {
  const sourceIndex = lbrnPaletteIndex(layer);
  if (sourceIndex !== null) {
    return sourceIndex >= 30 ? `T${sourceIndex - 29}` : String(sourceIndex).padStart(2, '0');
  }

  const colorTag = layer.color_tag;
  const norm = normalizeHex(colorTag);
  const idx = PALETTE_COLORS.findIndex(
    (c) => normalizeHex(c.hex) === norm,
  );
  if (idx >= 0) {
    const entry = PALETTE_COLORS[idx];
    if (entry.is_tool_layer) return `T${idx - 29}`;
    return String(idx).padStart(2, '0');
  }
  return '??';
}

function ToggleSwitch({
  active,
  activeColor,
  onClick,
  testId,
}: {
  active: boolean;
  activeColor?: string;
  onClick: () => void;
  testId?: string;
}) {
  return (
    <button
      onClick={(e) => { e.stopPropagation(); onClick(); }}
      onContextMenu={(e) => { e.preventDefault(); e.stopPropagation(); }}
      className={`relative w-7 h-3.5 rounded-full mx-auto transition-colors ${
        active ? (activeColor ?? 'bg-green-500') : 'bg-bb-text/20'
      }`}
      data-testid={testId}
    >
      <div className={`absolute top-0.5 w-2.5 h-2.5 rounded-full bg-white shadow transition-transform ${
        active ? 'translate-x-3.5' : 'translate-x-0.5'
      }`} />
    </button>
  );
}

function FrameToggle({
  active,
  onToggle,
}: {
  active: boolean;
  onToggle: () => void;
}) {
  const { t } = useTranslation();

  return (
    <button
      type="button"
      className="inline-flex w-full items-center justify-end gap-2 text-bb-text"
      onClick={(e) => {
        e.stopPropagation();
        onToggle();
      }}
      onContextMenu={(e) => {
        e.preventDefault();
        e.stopPropagation();
      }}
      title={
        active
          ? t('panels.layers.exclude_tool_layers_from_job_bounds')
          : t('panels.layers.include_tool_layers_in_job_bounds')
      }
      data-testid="frame-toggle"
    >
      <span
        className={`relative inline-flex w-7 h-3.5 shrink-0 rounded-full transition-colors ${
          active ? 'bg-green-500' : 'bg-bb-text/20'
        }`}
      >
        <span
          className={`absolute top-0.5 w-2.5 h-2.5 rounded-full bg-white shadow transition-transform ${
            active ? 'translate-x-3.5' : 'translate-x-0.5'
          }`}
        />
      </span>
      <span className="shrink-0">{t('panels.layers.frame')}</span>
    </button>
  );
}

export function LayerList() {
  const { t } = useTranslation();
  const layers = useProjectStore((s) => s.project?.layers ?? []);
  const selectedLayerId = useProjectStore((s) => s.selectedLayerId);
  const selectLayer = useProjectStore((s) => s.selectLayer);
  const updateLayer = useProjectStore((s) => s.updateLayer);
  const updateCutEntry = useProjectStore((s) => s.updateCutEntry);
  const lockObjects = useProjectStore((s) => s.lockObjects);
  const unlockObjects = useProjectStore((s) => s.unlockObjects);
  const reorderLayer = useProjectStore((s) => s.reorderLayer);
  const loadProject = useProjectStore((s) => s.loadProject);
  const includeToolLayersInJobBounds = useAppStore(
    (s) => s.settings?.include_tool_layers_in_job_bounds ?? true,
  );
  const updateSettings = useAppStore((s) => s.updateSettings);
  const currentAppSettings = useAppStore((s) => s.settings);
  const displayUnit = currentAppSettings?.display_unit === 'inches' ? 'inches' : 'mm';
  const speedTimeUnit = currentAppSettings?.speed_time_unit === 'seconds' ? 'seconds' : 'minutes';
  const speedLabel = speedUnitLabel(displayUnit, speedTimeUnit);
  const speedStep = speedStepForUnit(displayUnit, speedTimeUnit);
  const maxDisplaySpeed = speedMmMinToDisplay(50000, displayUnit, speedTimeUnit);
  const minDisplaySpeed = speedMmMinToDisplay(1, displayUnit, speedTimeUnit);
  const [optimisticToolFrameBounds, setOptimisticToolFrameBounds] = useState<boolean | null>(null);

  const [editingLayerId, setEditingLayerId] = useState<string | null>(null);
  const [contextMenu, setContextMenu] = useState<{ x: number; y: number; layerId: string } | null>(null);
  const [headerContextMenu, setHeaderContextMenu] = useState<{ x: number; y: number } | null>(null);
  const [renamingLayerId, setRenamingLayerId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState('');

  // M4: app-scoped clipboard via uiStore (replaces the old narrow component-local useRef).
  const copyLayerSettings = useProjectStore((s) => s.copyLayerSettings);
  const pasteLayerSettings = useProjectStore((s) => s.pasteLayerSettings);
  const setAllLayersEnabled = useProjectStore((s) => s.setAllLayersEnabled);
  const setAllLayersVisible = useProjectStore((s) => s.setAllLayersVisible);
  const sortLayersCutLast = useProjectStore((s) => s.sortLayersCutLast);
  const flashLayer = useUiStore((s) => s.flashLayer);
  const layerSettingsClipboard = useUiStore((s) => s.layerSettingsClipboard);

  const objects = useProjectStore((s) => s.project?.objects ?? []);
  const selectObjects = useProjectStore((s) => s.selectObjects);

  // Auto-close context menu on layer selection change
  useEffect(() => {
    if (contextMenu) {
      setContextMenu(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedLayerId]);

  /**
   * Compute visual family-cluster markers in flat list order. A
   * "family" is a run of consecutive layers sharing the same
   * normalized `color_tag`. `isFamilyStart[layerId]` is true iff
   * the row above has a different color (or it's the first row),
   * so the renderer can add a top-margin separator between
   * clusters. Families are derived purely from `color_tag` — no
   * persisted grouping, no reordering of the flat array (reorder
   * arrows still work on their flat indices).
   *
   * If an image row is dragged away from its vector sibling, the
   * two siblings just render as separate single-row clusters with
   * the same color accent. The layer-family resolver in the store
   * still treats them as one family for routing purposes because
   * it groups by color_tag, not adjacency.
   */
  const familyInfo = useMemo(() => {
    const isFamilyStart = new Map<string, boolean>();
    let prevColor: string | null = null;
    for (const l of layers) {
      const norm = normalizeHex(l.color_tag);
      isFamilyStart.set(l.id, norm !== prevColor);
      prevColor = norm;
    }
    return { isFamilyStart };
  }, [layers]);

  const selectedLayer = layers.find((l) => l.id === selectedLayerId) ?? null;
  const activeLayer = selectedLayer ?? layers[0] ?? null;

  const notifyLayerError = (messageKey: string, error: unknown) => {
    useNotificationStore.getState().push(t(messageKey, { detail: String(error) }), 'error');
  };

  const reloadLayers = async (invalidatePreview = false) => {
    try {
      await loadProject(invalidatePreview ? { invalidatePreview: true } : undefined);
    } catch (error) {
      notifyLayerError('panels.layers.errors.reload_layers', error);
    }
  };

  const handleToggleVisible = async (layerId: string, visible: boolean) => {
    try {
      await projectService.setLayerVisible(layerId, visible);
      await reloadLayers(true);
    } catch (error) {
      notifyLayerError('panels.layers.errors.update_visibility', error);
    }
  };

  const handleToggleAirAssist = async (layerId: string, airAssist: boolean) => {
    try {
      await projectService.setLayerAirAssist(layerId, airAssist);
      await reloadLayers(true);
    } catch (error) {
      notifyLayerError('panels.layers.errors.update_air_assist', error);
    }
  };

  const handleModeChange = async (layer: Layer, operation: OperationType) => {
    try {
      const entry = primaryEntry(layer);
      if (!entry) return;
      await projectService.updateCutEntry(layer.id, entry.id, { operation });
      await reloadLayers(true);
    } catch (error) {
      notifyLayerError('panels.layers.errors.update_mode', error);
    }
  };

  const getPassCount = (layer: Layer): number => {
    if (primaryVectorSettings(layer)) return primaryVectorSettings(layer)!.passes;
    if (primaryRasterSettings(layer)) return primaryRasterSettings(layer)!.passes;
    return 1;
  };

  const setPassCount = async (layer: Layer, passes: number) => {
    const entry = primaryEntry(layer);
    if (!entry) return;
    try {
      if (entry.raster_settings) {
        await projectService.updateCutEntry(layer.id, entry.id, {
          raster_settings: { ...entry.raster_settings, passes },
        });
      } else if (entry.vector_settings) {
        await projectService.updateCutEntry(layer.id, entry.id, {
          vector_settings: { ...entry.vector_settings, passes },
        });
      } else {
        return;
      }
      await reloadLayers(true);
    } catch (error) {
      notifyLayerError('panels.layers.errors.update_passes', error);
      await reloadLayers();
    }
  };

  const getInterval = (layer: Layer): number => {
    return Math.round(effectiveLineIntervalMm(primaryRasterSettings(layer)) * 1000) / 1000;
  };

  const setInterval = (layer: Layer, lineIntervalMm: number) => {
    const entry = primaryEntry(layer);
    if (!entry?.raster_settings) return;
    useProjectStore.getState().updateCutEntry(layer.id, entry.id, {
      raster_settings: {
        ...entry.raster_settings,
        line_interval_mm: lineIntervalMm,
        dpi: lineIntervalMm > 0 ? Math.round(25.4 / lineIntervalMm) : 254,
      },
    });
  };

  const isFillMode = (layer: Layer) =>
    !layer.is_tool_layer &&
    (layerOperation(layer) === 'fill' || layerOperation(layer) === 'offset_fill' || layerOperation(layer) === 'image');

  const isVectorMode = (layer: Layer) =>
    !layer.is_tool_layer &&
    (layerOperation(layer) === 'line' || layerOperation(layer) === 'cut' || layerOperation(layer) === 'score');

  const updateVectorSettings = async (layer: Layer, patch: Partial<VectorSettings>) => {
    const entry = primaryEntry(layer);
    const vs = entry?.vector_settings;
    if (!vs) return;
    try {
      await projectService.updateCutEntry(layer.id, entry.id, {
        vector_settings: { ...vs, ...patch },
      });
      await reloadLayers(true);
    } catch (error) {
      notifyLayerError('panels.layers.errors.update_vector_settings', error);
      await reloadLayers();
    }
  };

  // M4: full-stack copy/paste via app-scoped clipboard. Backend mints fresh entry IDs and
  // replaces the target layer's entries[] in one atomic op (one undo snapshot).
  const handleCopySettings = (layer: Layer) => {
    if (layer.is_tool_layer) return;
    copyLayerSettings(layer.id);
  };

  const handlePasteSettings = async (layerId: string) => {
    try {
      await pasteLayerSettings(layerId);
    } catch (error) {
      notifyLayerError('panels.layers.errors.paste_settings', error);
    }
  };

  const handleDisableAllButThis = (layerId: string) => {
    void setAllLayersEnabled({ kind: 'only_this_on', keep: layerId });
  };

  const handleHideAllButThis = (layerId: string) => {
    void setAllLayersVisible({ kind: 'only_this_on', keep: layerId });
  };

  const handleFlashLayer = (layerId: string) => {
    flashLayer(layerId);
  };

  const handleToggleToolFrameBounds = async () => {
    const currentValue = optimisticToolFrameBounds ?? includeToolLayersInJobBounds;
    const nextValue = !currentValue;
    setOptimisticToolFrameBounds(nextValue);
    if (currentAppSettings) {
      useAppStore.setState({
        settings: {
          ...currentAppSettings,
          include_tool_layers_in_job_bounds: nextValue,
        },
      });
    }
    try {
      await updateSettings({
        include_tool_layers_in_job_bounds: nextValue,
      });
      setOptimisticToolFrameBounds(null);
    } catch (error) {
      if (currentAppSettings) {
        useAppStore.setState({ settings: currentAppSettings });
      }
      setOptimisticToolFrameBounds(null);
      notifyLayerError('panels.layers.errors.update_tool_frame', error);
    }
  };

  const handleStartRename = (layerId: string) => {
    const layer = layers.find((l) => l.id === layerId);
    setRenamingLayerId(layerId);
    setRenameValue(layer?.name ?? '');
  };

  const handleCommitRename = async () => {
    if (renamingLayerId && renameValue.trim()) {
      const renamed = await updateLayer(renamingLayerId, { name: renameValue.trim() });
      if (!renamed) return;
    }
    setRenamingLayerId(null);
  };

  if (layers.length === 0) {
    return (
      <div className="flex flex-col">
        <div
          className={`grid items-center text-xs text-bb-text-dim uppercase px-1.5 py-1 border-b border-bb-border bg-bb-bg-alt ${COL_GAP}`}
          style={{ gridTemplateColumns: COL_TEMPLATE }}
        >
          <span>{t('panels.layers.header.index')}</span>
          <span>{t('panels.layers.header.layer')}</span>
          <span>{t('panels.layers.header.mode')}</span>
          <span className="text-right">{t('panels.layers.header.speed_power')}</span>
          <span />
        </div>
        <div className="px-2 py-3 text-xs text-bb-text-dim text-center" data-testid="empty-layer-row">
          {t('panels.layers.empty')}
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col">
      {/* Table header — right-click for batch actions / Sort Cuts Last (M4). */}
      <div
        className={`grid items-center text-xs text-bb-text-dim uppercase px-1.5 py-1 border-b border-bb-border bg-bb-bg-alt ${COL_GAP}`}
        style={{ gridTemplateColumns: COL_TEMPLATE }}
        data-testid="layer-table-header"
        onContextMenu={(e) => {
          e.preventDefault();
          setHeaderContextMenu({ x: e.clientX, y: e.clientY });
        }}
      >
        <span>{t('panels.layers.header.index')}</span>
        <span>{t('panels.layers.header.layer')}</span>
        <span>{t('panels.layers.header.mode')}</span>
        <span className="text-right">{t('panels.layers.header.speed_power')}</span>
        <span />
      </div>

      {/* Table rows — grouped visually by color_tag family.
          `isFamilyStart` marks the first row of each run so we can
          add a top margin + border-top separator between clusters. */}
      {layers.map((layer, index) => {
        const familyStart = familyInfo.isFamilyStart.get(layer.id) ?? true;
        const primaryEntry = layer.entries[0];
        const isImageRow = primaryEntry?.operation === 'image';
        const isMulti = layer.entries.length > 1;
        return (
        <div
          key={layer.id}
          className={`grid items-center text-xs px-1.5 py-1 cursor-pointer border-b border-bb-border ${COL_GAP} ${
            layer.id === selectedLayerId
              ? 'bg-bb-accent/20 text-bb-text'
              : 'text-bb-text-muted hover:bg-bb-bg'
          } ${familyStart && index > 0 ? 'mt-0.5 border-t border-bb-border' : ''}`}
          style={{
            gridTemplateColumns: COL_TEMPLATE,
            borderLeft: `3px solid ${layer.color_tag}`,
            paddingLeft: '0.375rem',
          }}
          onClick={(e) => {
            if (e.shiftKey) {
              const layerObjIds = objects
                .filter((object) => object.layer_id === layer.id)
                .map((object) => object.id)
                .reverse();
              selectObjects(layerObjIds);
              return;
            }
            selectLayer(layer.id);
          }}
          onDoubleClick={() => {
            if (!layer.is_tool_layer) setEditingLayerId(layer.id);
          }}
          onContextMenu={(e) => {
            e.preventDefault();
            e.stopPropagation();
            selectLayer(layer.id);
            if (e.shiftKey) {
              handleFlashLayer(layer.id);
              return;
            }
            // Set context menu after a microtask to avoid the auto-close from selectedLayerId change
            queueMicrotask(() => setContextMenu({ x: e.clientX, y: e.clientY, layerId: layer.id }));
          }}
          data-testid="layer-row"
          data-family-start={familyStart ? 'true' : undefined}
          data-image-row={isImageRow ? 'true' : undefined}
        >
          {/* # — Layer ID or inline rename input */}
          {renamingLayerId === layer.id ? (
            <input
              autoFocus
              className="text-xs font-mono bg-bb-input text-bb-text border border-bb-accent rounded px-0.5 w-full"
              value={renameValue}
              onChange={(e) => setRenameValue(e.target.value)}
              onBlur={() => { void handleCommitRename(); }}
              onKeyDown={(e) => {
                if (e.key === 'Enter') void handleCommitRename();
                if (e.key === 'Escape') setRenamingLayerId(null);
              }}
              onClick={(e) => e.stopPropagation()}
              data-testid="rename-input"
            />
          ) : (
            <span className="text-xs font-mono" data-testid="layer-label">
              {displayLayerName(layer)}
            </span>
          )}

          {/* Colored layer chip — image rows share the family
              number/color and render slightly darker, matching the
              paired-layer appearance. */}
          <div
            className="h-5 rounded-sm flex items-center justify-center text-[10px] font-bold"
            style={{
              backgroundColor: layer.color_tag,
              color: getContrastText(layer.color_tag),
              filter: isImageRow ? 'brightness(0.75)' : undefined,
            }}
            data-testid="color-swatch"
          >
            {getPaletteIndex(layer)}
          </div>

          {/* Mode — Tool/Image are immutable labels, vector ops stay editable. */}
          {isMulti ? (
            <span
              className="text-xs text-bb-text px-0.5 h-5 flex items-center"
              data-testid="mode-multi-label"
            >
              {t('panels.layers.mode.multi')}
            </span>
          ) : layer.is_tool_layer ? (
            <span
              className="text-xs text-bb-text px-0.5 h-5 flex items-center font-semibold"
              data-testid="mode-tool-label"
            >
              {t('panels.layers.mode.tool')}
            </span>
          ) : primaryEntry?.operation === 'image' ? (
            <span
              className="text-xs text-bb-text px-0.5 h-5 flex items-center"
              data-testid="mode-image-label"
            >
              {t('panels.layers.mode.image')}
            </span>
          ) : (
            <select
              className="bg-bb-input text-bb-text border border-bb-border rounded text-xs px-0.5 py-0 h-5 w-full min-w-0 truncate"
              value={primaryEntry?.operation ?? 'line'}
              onChange={(e) => {
                e.stopPropagation();
                void handleModeChange(layer, e.target.value as OperationType);
              }}
              onClick={(e) => e.stopPropagation()}
              onContextMenu={(e) => { e.preventDefault(); e.stopPropagation(); }}
              data-testid="mode-select"
            >
              {MODE_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {t(opt.labelKey)}
                </option>
              ))}
            </select>
          )}

          {/* Spd/Pwr */}
          <span className="text-xs text-bb-text-dim whitespace-nowrap text-right" data-testid="speed-power">
            {layer.is_tool_layer ? (
              <FrameToggle
                active={optimisticToolFrameBounds ?? includeToolLayersInJobBounds}
                onToggle={() => { void handleToggleToolFrameBounds(); }}
              />
            ) : (
              `${formatSpeedForDisplay(primaryEntry?.speed_mm_min ?? 1000, displayUnit, speedTimeUnit)}/${primaryEntry?.power_percent ?? 50}%${isMulti ? t('panels.layers.additional_entries', { count: layer.entries.length - 1 }) : ''}`
            )}
          </span>

          {/* Reorder arrows */}
          <div className="flex flex-col items-center" onContextMenu={(e) => { e.preventDefault(); e.stopPropagation(); }}>
            {index > 0 && (
              <button
                className="w-3.5 h-3.5 text-[10px] text-bb-text-dim/60 hover:text-bb-text leading-none"
                onClick={(e) => { e.stopPropagation(); void reorderLayer(layer.id, index - 1); }}
                title={t('panels.layers.move_up')}
                data-testid="move-up"
              >
                {MOVE_UP_ICON}
              </button>
            )}
            {index < layers.length - 1 && (
              <button
                className="w-3.5 h-3.5 text-[10px] text-bb-text-dim/60 hover:text-bb-text leading-none"
                onClick={(e) => { e.stopPropagation(); void reorderLayer(layer.id, index + 1); }}
                title={t('panels.layers.move_down')}
                data-testid="move-down"
              >
                {MOVE_DOWN_ICON}
              </button>
            )}
          </div>
        </div>
        );
      })}

      {/* Layer action buttons */}
      {activeLayer && (
        <div className="flex gap-1 px-1.5 py-1 border-b border-bb-border bg-bb-bg-alt" data-testid="layer-actions">
          <button
            data-testid="select-all-on-layer"
            className="p-1 rounded hover:bg-bb-hover text-bb-text-muted hover:text-bb-text"
            title={t('panels.layers.select_all_objects_title')}
            onClick={() => {
              const layerObjIds = objects
                .filter((o) => o.layer_id === activeLayer.id)
                .map((o) => o.id)
                .reverse();
              selectObjects(layerObjIds);
            }}
          >
            <CheckSquare size={16} />
          </button>
          <button
            data-testid="lock-layer"
            className="p-1 rounded hover:bg-bb-hover text-bb-text-muted hover:text-bb-text"
            title={t('panels.layers.toggle_lock_title')}
            onClick={() => {
              const layerObjs = objects.filter((o) => o.layer_id === activeLayer.id);
              const allLocked = layerObjs.length > 0 && layerObjs.every((o) => o.locked);
              const layerObjectIds = layerObjs.map((o) => o.id);
              if (layerObjectIds.length === 0) return;
              if (allLocked) {
                void unlockObjects(layerObjectIds);
              } else {
                void lockObjects(layerObjectIds);
              }
            }}
          >
            <Lock size={16} />
          </button>
          {/* M4: dedicated Copy/Paste side buttons for the Cuts/Layers panel. */}
          <button
            data-testid="copy-layer-settings"
            className="p-1 rounded hover:bg-bb-hover text-bb-text-muted hover:text-bb-text"
            title={t('panels.layers.copy_settings_title')}
            onClick={() => handleCopySettings(activeLayer)}
            disabled={activeLayer.is_tool_layer}
          >
            <ClipboardCopy size={16} />
          </button>
          <button
            data-testid="paste-layer-settings"
            className="p-1 rounded hover:bg-bb-hover text-bb-text-muted hover:text-bb-text disabled:opacity-40 disabled:cursor-not-allowed"
            title={
              layerSettingsClipboard && layerSettingsClipboard.length > 0
                ? t('panels.layers.paste_settings_title')
                : t('panels.layers.no_layer_settings_on_clipboard')
            }
            disabled={activeLayer.is_tool_layer || !layerSettingsClipboard || layerSettingsClipboard.length === 0}
            onClick={() => void handlePasteSettings(activeLayer.id)}
          >
            <ClipboardPaste size={16} />
          </button>
        </div>
      )}

      {/* Layer-level toggles for the selected layer (moved out of the rows) */}
      {activeLayer && (
        <div
          className="flex items-center gap-5 px-2 py-1.5 border-t-2 border-bb-border bg-bb-surface text-xs"
          data-testid="layer-toggles"
        >
          {!activeLayer.is_tool_layer && (
            <label className="flex items-center gap-1.5 text-bb-text-muted">
              {t('panels.layers.header.output')}
              <ToggleSwitch
                active={activeLayer.enabled}
                onClick={() => updateLayer(activeLayer.id, { enabled: !activeLayer.enabled })}
                testId="output-toggle"
              />
            </label>
          )}
          <label className="flex items-center gap-1.5 text-bb-text-muted">
            {t('panels.layers.header.show')}
            <ToggleSwitch
              active={activeLayer.visible !== false}
              activeColor={SHOW_TOGGLE_ACTIVE_COLOR}
              onClick={() => void handleToggleVisible(activeLayer.id, activeLayer.visible === false)}
              testId="show-toggle"
            />
          </label>
          {!activeLayer.is_tool_layer && (
            <label className="flex items-center gap-1.5 text-bb-text-muted">
              {t('panels.layers.header.air')}
              <ToggleSwitch
                active={primaryEntry(activeLayer)?.air_assist === true}
                activeColor={AIR_TOGGLE_ACTIVE_COLOR}
                onClick={() => void handleToggleAirAssist(activeLayer.id, !(primaryEntry(activeLayer)?.air_assist ?? false))}
                testId="air-toggle"
              />
            </label>
          )}
        </div>
      )}

      {/* Quick-edit section — always visible, shows selected or first layer */}
      {activeLayer && !activeLayer.is_tool_layer && (
        <div className="px-2 py-1.5 border-t-2 border-bb-border bg-bb-surface" data-testid="quick-edit">
          <div className="grid grid-cols-2 gap-x-3 gap-y-1">
            {/* Mode (Line / Fill / Offset Fill) for the selected layer */}
            <div className="flex items-center gap-1.5 text-xs">
              <span className="text-bb-text-muted shrink-0">{t('panels.layers.header.mode')}</span>
              {primaryEntry(activeLayer)?.operation === 'image' ? (
                <span className="text-xs text-bb-text">{t('panels.layers.mode.image')}</span>
              ) : (
                <select
                  className="bg-bb-input text-bb-text border border-bb-border rounded text-xs px-0.5 py-0 h-5 w-full min-w-0 truncate"
                  value={primaryEntry(activeLayer)?.operation ?? 'line'}
                  onChange={(e) => void handleModeChange(activeLayer, e.target.value as OperationType)}
                  data-testid="quick-edit-mode"
                >
                  {MODE_OPTIONS.map((opt) => (
                    <option key={opt.value} value={opt.value}>
                      {t(opt.labelKey)}
                    </option>
                  ))}
                </select>
              )}
            </div>
            {/* Color swatch (read-only — use palette bar to reassign) */}
            <div className="flex items-center gap-1.5 text-xs">
              <span className="text-bb-text-muted shrink-0">{t('panels.layers.quick_edit.color')}</span>
              <div
                className="w-5 h-4 rounded-sm border border-bb-border shrink-0"
                style={{ backgroundColor: activeLayer.color_tag }}
              />
            </div>

            {/* Speed */}
            <NumberInput
              label={t('panels.layers.quick_edit.speed_with_unit', { unit: speedLabel })}
              value={speedInputValue(primaryEntry(activeLayer)?.speed_mm_min ?? 1000, displayUnit, speedTimeUnit)}
              onChange={(v) => {
                const entry = primaryEntry(activeLayer);
                if (entry) void updateCutEntry(activeLayer.id, entry.id, {
                  speed_mm_min: displaySpeedToMmMin(v, displayUnit, speedTimeUnit),
                });
              }}
              min={minDisplaySpeed}
              max={maxDisplaySpeed}
              step={speedStep}
            />

            {/* Passes */}
            <NumberInput
              label={t('panels.layers.quick_edit.passes')}
              value={getPassCount(activeLayer)}
              onChange={(p) => { void setPassCount(activeLayer, p); }}
              min={1}
              step={1}
            />

            {/* Max Pwr */}
            <NumberInput
              label={t('panels.layers.quick_edit.max_power')}
              value={primaryEntry(activeLayer)?.power_percent ?? 50}
              onChange={(v) => {
                const entry = primaryEntry(activeLayer);
                if (entry) void updateCutEntry(activeLayer.id, entry.id, { power_percent: v });
              }}
              min={0}
              max={100}
              step={1}
            />

            {/* Interval — only for fill/image modes */}
            {isFillMode(activeLayer) && (
              <NumberInput
                label={labelWithUnit(t('panels.layers.quick_edit.interval'), lengthUnitLabel(displayUnit))}
                value={roundDisplayLength(mmToDisplay(getInterval(activeLayer), displayUnit), displayUnit)}
                onChange={(v) => setInterval(activeLayer, displayToMm(v, displayUnit))}
                min={mmToDisplay(0.01, displayUnit)}
                step={lengthStep(displayUnit, 0.01, 0.001)}
              />
            )}

            {/* Min Pwr */}
            <NumberInput
              label={t('panels.layers.quick_edit.min_power')}
              value={primaryEntry(activeLayer)?.power_min_percent ?? 0}
              onChange={(v) => {
                const entry = primaryEntry(activeLayer);
                if (entry) void updateCutEntry(activeLayer.id, entry.id, { power_min_percent: v });
              }}
              min={0}
              max={100}
              step={1}
            />
          </div>

          {/* Vector-only: perforation & kerf */}
          {isVectorMode(activeLayer) && primaryVectorSettings(activeLayer) && (
            <div className="mt-1.5 pt-1.5 border-t border-bb-border" data-testid="vector-quick-edit">
              <div className="grid grid-cols-2 gap-x-3 gap-y-1">
                <label className="flex items-center gap-1 text-xs col-span-2">
                  <input
                    type="checkbox"
                    checked={primaryVectorSettings(activeLayer)?.perforation_enabled ?? false}
                    onChange={(e) => { void updateVectorSettings(activeLayer, { perforation_enabled: e.target.checked }); }}
                    data-testid="perf-toggle"
                  />
                  {t('panels.layers.quick_edit.perforation')}
                </label>
                {primaryVectorSettings(activeLayer)?.perforation_enabled && (
                  <>
                    <NumberInput
                      label={t('panels.layers.quick_edit.on_ms')}
                      value={primaryVectorSettings(activeLayer)?.perforation_on_ms ?? 10}
                      onChange={(v) => { void updateVectorSettings(activeLayer, { perforation_on_ms: v }); }}
                      min={0}
                      step={1}
                    />
                    <NumberInput
                      label={t('panels.layers.quick_edit.off_ms')}
                      value={primaryVectorSettings(activeLayer)?.perforation_off_ms ?? 10}
                      onChange={(v) => { void updateVectorSettings(activeLayer, { perforation_off_ms: v }); }}
                      min={0}
                      step={1}
                    />
                  </>
                )}
                <NumberInput
                  label={labelWithUnit(t('panels.layers.quick_edit.kerf_mm'), lengthUnitLabel(displayUnit))}
                  value={roundDisplayLength(mmToDisplay(primaryVectorSettings(activeLayer)?.kerf_offset_mm ?? 0, displayUnit), displayUnit)}
                  onChange={(v) => { void updateVectorSettings(activeLayer, { kerf_offset_mm: displayToMm(v, displayUnit) || undefined }); }}
                  min={0}
                  step={lengthStep(displayUnit, 0.01, 0.001)}
                />
              </div>
            </div>
          )}
        </div>
      )}

      {/* CutSettingsEditor dialog */}
      {editingLayerId && (
        <CutSettingsEditor
          layerId={editingLayerId}
          onClose={() => setEditingLayerId(null)}
          onSwitchLayer={(newId) => setEditingLayerId(newId)}
        />
      )}

      {/* Layer context menu */}
      {contextMenu && (() => {
        const ctxLayer = layers.find((l) => l.id === contextMenu.layerId);
        if (!ctxLayer) return null;
        return (
          <ContextMenu
            x={contextMenu.x}
            y={contextMenu.y}
            items={buildLayerContextMenuItems(t, ctxLayer, objects, {
              toggleEnabled: (layerId, enabled) => updateLayer(layerId, { enabled }),
              toggleVisible: (layerId, visible) => void handleToggleVisible(layerId, visible),
              selectObjects,
              copySettings: handleCopySettings,
              pasteSettings: (layerId) => void handlePasteSettings(layerId),
              startRename: handleStartRename,
              hasClipboard: layerSettingsClipboard !== null && layerSettingsClipboard.length > 0,
              disableAllButThis: handleDisableAllButThis,
              hideAllButThis: handleHideAllButThis,
              flashLayer: handleFlashLayer,
            })}
            onClose={() => setContextMenu(null)}
          />
        );
      })()}

      {/* M4: header context menu — Enable/Disable/Invert all + Show/Hide/Invert all + Sort Cuts Last. */}
      {headerContextMenu && (
        <ContextMenu
          x={headerContextMenu.x}
          y={headerContextMenu.y}
          items={buildLayerListHeaderMenuItems(t, {
            setAllLayersEnabled: (mode) => void setAllLayersEnabled(mode),
            setAllLayersVisible: (mode) => void setAllLayersVisible(mode),
            sortLayersCutLast: () => void sortLayersCutLast(),
          })}
          onClose={() => setHeaderContextMenu(null)}
        />
      )}
    </div>
  );
}
