import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bb-bg': 'rgb(var(--bb-bg) / <alpha-value>)',
        'bb-bg-alt': 'rgb(var(--bb-bg-alt) / <alpha-value>)',
        'bb-input': 'rgb(var(--bb-input) / <alpha-value>)',
        'bb-panel': 'rgb(var(--bb-panel) / <alpha-value>)',
        'bb-panel-header': 'rgb(var(--bb-panel-header) / <alpha-value>)',
        'bb-surface': 'rgb(var(--bb-surface) / <alpha-value>)',
        'bb-surface-2': 'rgb(var(--bb-surface-2) / <alpha-value>)',
        'bb-surface-3': 'rgb(var(--bb-surface-3) / <alpha-value>)',
        'bb-surface-elevated': 'rgb(var(--bb-surface-elevated) / <alpha-value>)',
        'bb-border': 'rgb(var(--bb-border) / <alpha-value>)',
        'bb-control-border': 'rgb(var(--bb-control-border) / <alpha-value>)',
        'bb-hover': 'rgb(var(--bb-hover) / <alpha-value>)',
        'bb-accent': 'rgb(var(--bb-accent) / <alpha-value>)',
        'bb-accent-hover': 'rgb(var(--bb-accent-hover) / <alpha-value>)',
        'bb-on-accent': 'rgb(var(--bb-on-accent) / <alpha-value>)',
        'bb-error': 'rgb(var(--bb-error) / <alpha-value>)',
        'bb-error-hover': 'rgb(var(--bb-error-hover) / <alpha-value>)',
        'bb-on-error': 'rgb(var(--bb-on-error) / <alpha-value>)',
        'bb-warning': 'rgb(var(--bb-warning) / <alpha-value>)',
        'bb-warning-hover': 'rgb(var(--bb-warning-hover) / <alpha-value>)',
        'bb-on-warning': 'rgb(var(--bb-on-warning) / <alpha-value>)',
        'bb-success': 'rgb(var(--bb-success) / <alpha-value>)',
        'bb-success-hover': 'rgb(var(--bb-success-hover) / <alpha-value>)',
        'bb-on-success': 'rgb(var(--bb-on-success) / <alpha-value>)',
        'bb-error-fg': 'rgb(var(--bb-error-fg) / <alpha-value>)',
        'bb-error-bg': 'rgb(var(--bb-error-bg) / <alpha-value>)',
        'bb-error-border': 'rgb(var(--bb-error-border) / <alpha-value>)',
        'bb-warning-fg': 'rgb(var(--bb-warning-fg) / <alpha-value>)',
        'bb-warning-bg': 'rgb(var(--bb-warning-bg) / <alpha-value>)',
        'bb-warning-border': 'rgb(var(--bb-warning-border) / <alpha-value>)',
        'bb-success-fg': 'rgb(var(--bb-success-fg) / <alpha-value>)',
        'bb-success-bg': 'rgb(var(--bb-success-bg) / <alpha-value>)',
        'bb-success-border': 'rgb(var(--bb-success-border) / <alpha-value>)',
        'bb-info-fg': 'rgb(var(--bb-info-fg) / <alpha-value>)',
        'bb-info-bg': 'rgb(var(--bb-info-bg) / <alpha-value>)',
        'bb-info-border': 'rgb(var(--bb-info-border) / <alpha-value>)',
        'bb-text': 'rgb(var(--bb-text) / <alpha-value>)',
        'bb-text-muted': 'rgb(var(--bb-text-muted) / <alpha-value>)',
        'bb-muted': 'rgb(var(--bb-text-muted) / <alpha-value>)',
        'bb-text-dim': 'rgb(var(--bb-text-dim) / <alpha-value>)',
        'bb-text-disabled': 'rgb(var(--bb-text-disabled) / <alpha-value>)',
      },
      fontSize: {
        'xxs': ['0.6875rem', { lineHeight: '1rem' }],
        'xs': ['0.8125rem', { lineHeight: '1.125rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
